### ISSUE TITLE
#autoLOC_

### ISSUE THREAD

**Issue by heichang** [shuwn/KSP-Traditional-Chinese#1]
在遊戲開始時，短暫出現了「載入中」字樣，但之後所有文字便都成為了#autoLOC_(數字)

**Comment by shuwn** [comment]
@heichang 麻煩請先確認是否有先設置為『簡體中文』，再套用本繁體中文翻譯，謝謝～

PS: 另外如果能提供截圖會比較好判斷原因

**Comment by heichang** [comment]
在刪除部份相關MOD與重裝遊戲後，問題已解決，THX
